# Generated by Django 5.2.1 on 2025-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Fungal', 'Fungal'), ('Bacterial', 'Bacterial'), ('Viral', 'Viral')], max_length=20)),
                ('symptoms', models.TextField()),
                ('distribution', models.CharField(max_length=200)),
                ('favoured_by', models.CharField(max_length=200)),
                ('similar_to', models.CharField(max_length=200)),
                ('control_strategies', models.TextField()),
                ('life_cycle', models.TextField()),
                ('impact', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('life_cycle', models.TextField()),
                ('damage_description', models.TextField()),
                ('importance', models.TextField()),
                ('hosts', models.CharField(max_length=200)),
                ('critical_control_period', models.CharField(max_length=100)),
                ('monitoring', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
