# Generated by Django 5.2.1 on 2025-05-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='type',
            new_name='disease_type',
        ),
    ]
