# Generated by Django 5.2.1 on 2025-05-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_type_disease_disease_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_type',
            field=models.CharField(choices=[('Fungal', 'Fungal'), ('Bacterial', 'Bacterial'), ('Viral', 'Viral'), ('Hello', 'Hello')], max_length=20),
        ),
    ]
