# Generated by Django 5.2.1 on 2025-05-28 23:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the farm's name.", max_length=100)),
                ('farm_address', models.CharField(blank=True, help_text="Enter the farm's address.", max_length=255)),
                ('contact_number', models.CharField(blank=True, help_text='Enter a valid contact number.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, dashes, and optional leading +).', regex='^\\+?[\\d\\s\\-]{7,20}$')])),
                ('notes', models.TextField(blank=True, help_text='Additional notes (optional).')),
                ('owner', models.ForeignKey(help_text='Farm owner (user account).', on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Select a date between 01/01/2000 and today.')),
                ('notes', models.TextField(help_text="Notes taken during survey. Type 'N/A' if none.", max_length=1000)),
                ('image', models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to='survey/')),
                ('diseases_found', models.ManyToManyField(blank=True, help_text='Select all diseases found (if any).', to='catalog.disease')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_records', to='survey.farm')),
                ('inspector', models.ForeignKey(blank=True, help_text='The user who conducted the surveillance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pests_found', models.ManyToManyField(blank=True, help_text='Select all pests found (if any).', to='catalog.pest')),
            ],
        ),
    ]
