# Generated by Django 5.2.1 on 2025-05-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillancerecord',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
