# Generated by Django 5.2.1 on 2025-05-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='land_area',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Land area (acres or hectares).', max_digits=10),
        ),
        migrations.AddField(
            model_name='farm',
            name='num_trees_est',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of trees.', verbose_name='Number of Trees (Estimated)'),
        ),
    ]
