# Generated by Django 5.2.1 on 2025-05-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_farm_land_area_farm_num_trees_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancerecord',
            name='num_trees_inspected',
            field=models.PositiveIntegerField(default=0, help_text='Enter the number of trees inspected during this survey.', verbose_name='Number of Trees Inspected'),
        ),
    ]
