# Generated by Django 5.2.1 on 2025-05-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveillancerecord_num_trees_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancerecord',
            name='time',
            field=models.TimeField(blank=True, help_text='Select the time of inspection.', null=True),
        ),
    ]
