# Generated by Django 5.2.1 on 2025-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveillancerecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillancerecord',
            name='time',
            field=models.TimeField(auto_now_add=True, help_text='Select the time of inspection.'),
        ),
    ]
